USUAL_OFFSET = 32

BEGIN_CAPITAL_LETTERS = 65
END_CAPITAL_LETTERS = 90

BEGIN_LOWER_CASE_LETTERS = BEGIN_CAPITAL_LETTERS + USUAL_OFFSET
END_LOWER_CASE_LETTERS = END_CAPITAL_LETTERS + USUAL_OFFSET

BEGIN_CAPITAL_SPECIAL_LETTERS = 128
END_CAPITAL_SPECIAL_LETTERS = 156

BEGIN_LOWER_CASE_SPECIAL_LETTERS = BEGIN_CAPITAL_SPECIAL_LETTERS + USUAL_OFFSET
END_LOWER_CASE_SPECIAL_LETTERS = END_CAPITAL_SPECIAL_LETTERS + USUAL_OFFSET

BEGIN_NUMBERS = 48
END_NUMBERS = 57

CR = 13
LF = 10
SPACE = 32
